"""建筑模板定义 - 所有建筑类型及其属性"""

from typing import Dict, Any


# 建筑模板
# 每个模板包含建筑的全部初始属性
BUILDING_TEMPLATES: Dict[str, Dict[str, Any]] = {
    "工厂": {
        "name": "工厂",
        "width": 2, "height": 2,
        "color": "blue",
        "description": "生产建筑，消耗铁和煤炭产出钢材",
        "max_hp": 200,
        "power_consumption": 15.0,
        "speed": 1.0,
        "efficiency": 1.0,
        "quality": 1.0,
        "pollution": 8.0,
        "freshness": 1.0,
        "weight": 500,
        "plugin_slots": 2,
        "construction_materials": {"iron": 10, "stone": 5},
        "inputs": {"iron": 2, "coal": 1},
        "outputs": {"steel": 1},
    },
    "住宅": {
        "name": "住宅",
        "width": 1, "height": 1,
        "color": "green",
        "description": "居住建筑，提供人口容量",
        "max_hp": 50,
        "power_consumption": 2.0,
        "speed": 0,
        "efficiency": 0,
        "quality": 0,
        "pollution": 0,
        "freshness": 1.0,
        "weight": 80,
        "plugin_slots": 0,
        "construction_materials": {"wood": 5, "stone": 2},
        "inputs": {},
        "outputs": {},
    },
    "仓库": {
        "name": "仓库",
        "width": 2, "height": 1,
        "color": "yellow",
        "description": "存储建筑，扩展物品存储容量",
        "max_hp": 150,
        "power_consumption": 1.0,
        "speed": 0,
        "efficiency": 0,
        "quality": 0,
        "pollution": 0.5,
        "freshness": 1.0,
        "weight": 300,
        "plugin_slots": 1,
        "construction_materials": {"wood": 8, "stone": 4},
        "inputs": {},
        "outputs": {},
    },
    "研究所": {
        "name": "研究所",
        "width": 2, "height": 2,
        "color": "cyan",
        "description": "科技建筑，研究新技术",
        "max_hp": 180,
        "power_consumption": 20.0,
        "speed": 1.0,
        "efficiency": 1.2,
        "quality": 1.5,
        "pollution": 3.0,
        "freshness": 1.0,
        "weight": 400,
        "plugin_slots": 3,
        "construction_materials": {"steel": 8, "stone": 4},
        "inputs": {"steel": 1},
        "outputs": {"key": 1},
    },
    "城墙": {
        "name": "城墙",
        "width": 3, "height": 1,
        "color": "gray",
        "description": "防御建筑，阻挡敌人",
        "max_hp": 500,
        "power_consumption": 0,
        "speed": 0,
        "efficiency": 0,
        "quality": 0,
        "pollution": 0,
        "freshness": 1.0,
        "weight": 1000,
        "plugin_slots": 0,
        "construction_materials": {"stone": 10},
        "inputs": {},
        "outputs": {},
    },
}

# 建筑名称列表（方便遍历）
BUILDING_NAMES = list(BUILDING_TEMPLATES.keys())
