"""建筑模板定义 - 所有建筑类型及其属性"""

from typing import Dict, Any


BUILDING_TEMPLATES: Dict[str, Dict[str, Any]] = {
    "工厂": {
        "name": "工厂", "width": 2, "height": 2,
        "color": "blue", "description": "生产建筑，消耗铁和煤炭产出钢材",
        "max_hp": 200, "power_consumption": 15.0,
        "speed": 1.0, "efficiency": 1.0, "quality": 1.0, "pollution": 8.0,
        "freshness": 1.0, "weight": 500, "plugin_slots": 2,
        "construction_materials": {"iron": 10, "stone": 5},
        "inputs": {"iron": 2, "coal": 1}, "outputs": {"steel": 1},
    },
    "住宅": {
        "name": "住宅", "width": 1, "height": 1,
        "color": "green", "description": "居住建筑，提供人口容量",
        "max_hp": 50, "power_consumption": 2.0,
        "speed": 1.0, "efficiency": 1.0, "quality": 1.0, "pollution": 0,
        "freshness": 1.0, "weight": 80, "plugin_slots": 0,
        "construction_materials": {"wood": 5, "stone": 2},
        "inputs": {}, "outputs": {},
    },
    "仓库": {
        "name": "仓库", "width": 2, "height": 1,
        "color": "yellow", "description": "存储建筑，扩展物品存储容量",
        "max_hp": 150, "power_consumption": 1.0,
        "speed": 1.0, "efficiency": 1.0, "quality": 1.0, "pollution": 0.5,
        "freshness": 1.0, "weight": 300, "plugin_slots": 1,
        "construction_materials": {"wood": 8, "stone": 4},
        "inputs": {}, "outputs": {},
    },
    "研究所": {
        "name": "研究所", "width": 2, "height": 2,
        "color": "cyan", "description": "科技建筑，研究新技术",
        "max_hp": 180, "power_consumption": 20.0,
        "speed": 1.0, "efficiency": 1.2, "quality": 1.5, "pollution": 3.0,
        "freshness": 1.0, "weight": 400, "plugin_slots": 3,
        "construction_materials": {"steel": 8, "stone": 4},
        "inputs": {"steel": 1}, "outputs": {"key": 1},
    },
    "城墙": {
        "name": "城墙", "width": 3, "height": 1,
        "color": "gray", "description": "防御建筑，阻挡敌人",
        "max_hp": 500, "power_consumption": 0,
        "speed": 1.0, "efficiency": 1.0, "quality": 1.0, "pollution": 0,
        "freshness": 1.0, "weight": 1000, "plugin_slots": 0,
        "construction_materials": {"stone": 10},
        "inputs": {}, "outputs": {},
    },
    "苹果工厂": {
        "name": "苹果工厂", "width": 2, "height": 2,
        "color": "red", "description": "消耗煤炭生产苹果",
        "max_hp": 120, "power_consumption": 8.0,
        "speed": 1.0, "efficiency": 1.0, "quality": 1.0, "pollution": 2.0,
        "freshness": 1.0, "weight": 300, "plugin_slots": 1,
        "construction_materials": {"iron": 5, "wood": 5},
        "inputs": {"coal": 2}, "outputs": {"apple": 3},
    },
    # ═══════════════════ 机械臂 ═══════════════════
    "热能机械臂": {
        "name": "热能机械臂", "width": 1, "height": 1,
        "color": "brown", "description": "烧煤/木工作，无需电力",
        "max_hp": 40, "power_consumption": 0,
        "speed": 1.0, "efficiency": 0, "quality": 0, "pollution": 2.0,
        "freshness": 1.0, "weight": 50, "plugin_slots": 0,
        "construction_materials": {"iron": 3},
        "inputs": {}, "outputs": {},
        "reach": 1, "inserter_speed": 45, "stack_size": 1,
        "uses_fuel": True, "fuel_max": 100, "filter": [],
    },
    "电力机械臂": {
        "name": "电力机械臂", "width": 1, "height": 1,
        "color": "yellow", "description": "基础电力机械臂",
        "max_hp": 50, "power_consumption": 5.0,
        "speed": 1.0, "efficiency": 0, "quality": 0, "pollution": 0,
        "freshness": 1.0, "weight": 40, "plugin_slots": 0,
        "construction_materials": {"iron": 5},
        "inputs": {}, "outputs": {},
        "reach": 1, "inserter_speed": 30, "stack_size": 1,
        "uses_fuel": False, "filter": [],
    },
    "加长机械臂": {
        "name": "加长机械臂", "width": 1, "height": 1,
        "color": "red", "description": "抓取距离2格",
        "max_hp": 60, "power_consumption": 8.0,
        "speed": 1.0, "efficiency": 0, "quality": 0, "pollution": 0,
        "freshness": 1.0, "weight": 50, "plugin_slots": 0,
        "construction_materials": {"iron": 8, "steel": 2},
        "inputs": {}, "outputs": {},
        "reach": 2, "inserter_speed": 24, "stack_size": 1,
        "uses_fuel": False, "filter": [],
    },
    "高速机械臂": {
        "name": "高速机械臂", "width": 1, "height": 1,
        "color": "blue", "description": "高速搬运，中后期主力",
        "max_hp": 70, "power_consumption": 12.0,
        "speed": 1.0, "efficiency": 0, "quality": 0, "pollution": 0,
        "freshness": 1.0, "weight": 60, "plugin_slots": 1,
        "construction_materials": {"iron": 10, "steel": 5},
        "inputs": {}, "outputs": {},
        "reach": 1, "inserter_speed": 15, "stack_size": 1,
        "uses_fuel": False, "filter": [],
    },
    "筛选机械臂": {
        "name": "筛选机械臂", "width": 1, "height": 1,
        "color": "purple", "description": "可设置物品白名单过滤",
        "max_hp": 70, "power_consumption": 14.0,
        "speed": 1.0, "efficiency": 0, "quality": 0, "pollution": 0,
        "freshness": 1.0, "weight": 65, "plugin_slots": 0,
        "construction_materials": {"iron": 10, "steel": 5, "key": 1},
        "inputs": {}, "outputs": {},
        "reach": 1, "inserter_speed": 15, "stack_size": 1,
        "uses_fuel": False, "filter": [],
    },
    "集装机械臂": {
        "name": "集装机械臂", "width": 1, "height": 1,
        "color": "green", "description": "一次抓取多件",
        "max_hp": 80, "power_consumption": 16.0,
        "speed": 1.0, "efficiency": 0, "quality": 0, "pollution": 0,
        "freshness": 1.0, "weight": 70, "plugin_slots": 1,
        "construction_materials": {"iron": 15, "steel": 8},
        "inputs": {}, "outputs": {},
        "reach": 1, "inserter_speed": 15, "stack_size": 4,
        "uses_fuel": False, "filter": [],
    },
    "集装筛选机械臂": {
        "name": "集装筛选机械臂", "width": 1, "height": 1,
        "color": "deep_purple", "description": "顶配，堆叠+过滤",
        "max_hp": 90, "power_consumption": 18.0,
        "speed": 1.0, "efficiency": 0, "quality": 0, "pollution": 0,
        "freshness": 1.0, "weight": 75, "plugin_slots": 1,
        "construction_materials": {"iron": 20, "steel": 10, "key": 3},
        "inputs": {}, "outputs": {},
        "reach": 1, "inserter_speed": 12, "stack_size": 6,
        "uses_fuel": False, "filter": [],
    },
    # ═══════════════════ 传送带 ═══════════════════
    "基础传送带": {
        "name": "基础传送带", "width": 1, "height": 1,
        "color": "yellow", "description": "基础物流，15件/秒，双车道",
        "max_hp": 20, "power_consumption": 0,
        "speed": 1.0, "efficiency": 0, "quality": 0, "pollution": 0,
        "freshness": 1.0, "weight": 30, "plugin_slots": 0,
        "construction_materials": {"iron": 3},
        "inputs": {}, "outputs": {}, "belt_tier": 1,
    },
    "高速传送带": {
        "name": "高速传送带", "width": 1, "height": 1,
        "color": "red", "description": "中型总线，30件/秒",
        "max_hp": 30, "power_consumption": 0,
        "speed": 1.0, "efficiency": 0, "quality": 0, "pollution": 0,
        "freshness": 1.0, "weight": 40, "plugin_slots": 0,
        "construction_materials": {"iron": 5, "steel": 2},
        "inputs": {}, "outputs": {}, "belt_tier": 2,
    },
    "极速传送带": {
        "name": "极速传送带", "width": 1, "height": 1,
        "color": "blue", "description": "大型总线，45件/秒",
        "max_hp": 40, "power_consumption": 0,
        "speed": 1.0, "efficiency": 0, "quality": 0, "pollution": 0,
        "freshness": 1.0, "weight": 50, "plugin_slots": 0,
        "construction_materials": {"iron": 10, "steel": 5},
        "inputs": {}, "outputs": {}, "belt_tier": 3,
    },
    "基础地下传送带": {
        "name": "基础地下传送带", "width": 1, "height": 1,
        "color": "yellow", "description": "跨越障碍，最大4格",
        "max_hp": 30, "power_consumption": 0,
        "speed": 1.0, "efficiency": 0, "quality": 0, "pollution": 0,
        "freshness": 1.0, "weight": 40, "plugin_slots": 0,
        "construction_materials": {"iron": 5},
        "inputs": {}, "outputs": {}, "belt_tier": 1,
    },
    "高速地下传送带": {
        "name": "高速地下传送带", "width": 1, "height": 1,
        "color": "red", "description": "跨越障碍，最大6格",
        "max_hp": 40, "power_consumption": 0,
        "speed": 1.0, "efficiency": 0, "quality": 0, "pollution": 0,
        "freshness": 1.0, "weight": 50, "plugin_slots": 0,
        "construction_materials": {"iron": 8, "steel": 3},
        "inputs": {}, "outputs": {}, "belt_tier": 2,
    },
    "极速地下传送带": {
        "name": "极速地下传送带", "width": 1, "height": 1,
        "color": "blue", "description": "跨越障碍，最大8格",
        "max_hp": 50, "power_consumption": 0,
        "speed": 1.0, "efficiency": 0, "quality": 0, "pollution": 0,
        "freshness": 1.0, "weight": 60, "plugin_slots": 0,
        "construction_materials": {"iron": 12, "steel": 6},
        "inputs": {}, "outputs": {}, "belt_tier": 3,
    },
    "基础分流器": {
        "name": "基础分流器", "width": 1, "height": 1,
        "color": "yellow", "description": "均分/合并/过滤",
        "max_hp": 40, "power_consumption": 0,
        "speed": 1.0, "efficiency": 0, "quality": 0, "pollution": 0,
        "freshness": 1.0, "weight": 50, "plugin_slots": 0,
        "construction_materials": {"iron": 5, "stone": 3},
        "inputs": {}, "outputs": {}, "belt_tier": 1,
    },
    "高速分流器": {
        "name": "高速分流器", "width": 1, "height": 1,
        "color": "red", "description": "均分/优先/过滤",
        "max_hp": 50, "power_consumption": 0,
        "speed": 1.0, "efficiency": 0, "quality": 0, "pollution": 0,
        "freshness": 1.0, "weight": 60, "plugin_slots": 0,
        "construction_materials": {"iron": 8, "steel": 4},
        "inputs": {}, "outputs": {}, "belt_tier": 2,
    },
    "极速分流器": {
        "name": "极速分流器", "width": 1, "height": 1,
        "color": "blue", "description": "均分/优先/过滤",
        "max_hp": 60, "power_consumption": 0,
        "speed": 1.0, "efficiency": 0, "quality": 0, "pollution": 0,
        "freshness": 1.0, "weight": 70, "plugin_slots": 0,
        "construction_materials": {"iron": 12, "steel": 6},
        "inputs": {}, "outputs": {}, "belt_tier": 3,
    },
    # ═══════════════════ 生产建筑 ═══════════════════
    "组装机1": {
        "name": "组装机1", "width": 2, "height": 2,
        "color": "yellow", "description": "基础自动生产",
        "max_hp": 80, "power_consumption": 10.0,
        "speed": 0.5, "efficiency": 1.0, "quality": 1.0, "pollution": 2.0,
        "freshness": 1.0, "weight": 150, "plugin_slots": 0,
        "construction_materials": {"iron": 5, "steel": 3},
        "inputs": {}, "outputs": {},
    },
    "组装机2": {
        "name": "组装机2", "width": 2, "height": 2,
        "color": "red", "description": "中级自动生产",
        "max_hp": 120, "power_consumption": 15.0,
        "speed": 0.75, "efficiency": 1.0, "quality": 1.0, "pollution": 3.0,
        "freshness": 1.0, "weight": 200, "plugin_slots": 1,
        "construction_materials": {"iron": 10, "steel": 5},
        "inputs": {}, "outputs": {},
    },
    "组装机3": {
        "name": "组装机3", "width": 2, "height": 2,
        "color": "blue", "description": "高级自动生产",
        "max_hp": 160, "power_consumption": 20.0,
        "speed": 1.25, "efficiency": 1.0, "quality": 1.0, "pollution": 4.0,
        "freshness": 1.0, "weight": 250, "plugin_slots": 2,
        "construction_materials": {"iron": 15, "steel": 10, "key": 2},
        "inputs": {}, "outputs": {},
    },
    "石熔炉": {
        "name": "石熔炉", "width": 2, "height": 2,
        "color": "gray", "description": "基础冶炼",
        "max_hp": 60, "power_consumption": 0,
        "speed": 1.0, "efficiency": 1.0, "quality": 1.0, "pollution": 5.0,
        "freshness": 1.0, "weight": 200, "plugin_slots": 0,
        "construction_materials": {"stone": 10},
        "inputs": {}, "outputs": {},
    },
    "电熔炉": {
        "name": "电熔炉", "width": 2, "height": 2,
        "color": "cyan", "description": "电动冶炼",
        "max_hp": 100, "power_consumption": 15.0,
        "speed": 2.0, "efficiency": 1.0, "quality": 1.0, "pollution": 3.0,
        "freshness": 1.0, "weight": 250, "plugin_slots": 1,
        "construction_materials": {"steel": 10, "stone": 5},
        "inputs": {}, "outputs": {},
    },
    "炼油厂": {
        "name": "炼油厂", "width": 3, "height": 3,
        "color": "brown", "description": "石油加工",
        "max_hp": 150, "power_consumption": 20.0,
        "speed": 1.0, "efficiency": 1.0, "quality": 1.0, "pollution": 8.0,
        "freshness": 1.0, "weight": 400, "plugin_slots": 2,
        "construction_materials": {"steel": 15, "stone": 10},
        "inputs": {}, "outputs": {},
    },
    "实验室": {
        "name": "实验室", "width": 2, "height": 2,
        "color": "white", "description": "消耗科研瓶进行研究",
        "max_hp": 80, "power_consumption": 10.0,
        "speed": 1.0, "efficiency": 1.0, "quality": 1.0, "pollution": 1.0,
        "freshness": 1.0, "weight": 150, "plugin_slots": 1,
        "construction_materials": {"iron": 10, "steel": 5},
        "inputs": {}, "outputs": {},
    },
    # ═══════ DLC 建筑 ═══════
    "铸造厂": {
        "name": "铸造厂", "width": 3, "height": 3,
        "color": "orange", "description": "Vulcanus 大型铸造",
        "max_hp": 250, "power_consumption": 30.0,
        "speed": 2.0, "efficiency": 1.5, "quality": 1.5, "pollution": 6.0,
        "freshness": 1.0, "weight": 600, "plugin_slots": 3,
        "construction_materials": {"tungsten": 15, "steel": 20},
        "inputs": {}, "outputs": {},
    },
    "电磁工厂": {
        "name": "电磁工厂", "width": 3, "height": 3,
        "color": "purple", "description": "Fulgora 电磁增产",
        "max_hp": 200, "power_consumption": 40.0,
        "speed": 1.5, "efficiency": 2.0, "quality": 1.5, "pollution": 4.0,
        "freshness": 1.0, "weight": 500, "plugin_slots": 3,
        "construction_materials": {"holmium": 15, "super_capacitor": 5},
        "inputs": {}, "outputs": {},
    },
    "生物舱": {
        "name": "生物舱", "width": 3, "height": 3,
        "color": "green", "description": "Gleba 生物培养",
        "max_hp": 180, "power_consumption": 25.0,
        "speed": 1.5, "efficiency": 1.5, "quality": 1.0, "pollution": 2.0,
        "freshness": 1.0, "weight": 450, "plugin_slots": 2,
        "construction_materials": {"steel": 20, "key": 5},
        "inputs": {}, "outputs": {},
    },
    "低温工厂": {
        "name": "低温工厂", "width": 3, "height": 3,
        "color": "light_blue", "description": "Aquilo 低温生产",
        "max_hp": 220, "power_consumption": 50.0,
        "speed": 2.0, "efficiency": 1.5, "quality": 2.0, "pollution": 1.0,
        "freshness": 1.0, "weight": 550, "plugin_slots": 3,
        "construction_materials": {"quantum_chip": 5, "steel": 25},
        "inputs": {}, "outputs": {},
    },
}

BUILDING_NAMES = list(BUILDING_TEMPLATES.keys())
